name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Debug git
        working-directory: ${{ github.workspace }}/QMServer
        run: |
          pwd
          ls -la
          git status

      - name: Install Python and dependencies
        working-directory: ${{ github.workspace }}/QMServer
        run: |
          apt-get update
          apt-get install -y python3 python3-pip git
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install -r requirements-dev.txt --break-system-packages

      - name: Run semantic-release
        working-directory: ${{ github.workspace }}/QMServer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m semantic_release publish