name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: /app

      - name: Install System Dependencies (Python, Pip, Git)
        working-directory: /app
        run: |
          apt-get update
          apt-get install -y python3 python3-pip git

      - name: Debug git
        working-directory: /app
        run: |
          pwd
          ls -la
          git status

      - name: Install Python Package Dependencies
        working-directory: /app
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install -r requirements-dev.txt --break-system-packages

      - name: Run semantic-release
        working-directory: /app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m semantic_release publish